### ISSUE TITLE
Change font of inputs

### ISSUE THREAD

**Issue by lucasriondel** [checkout/frames-react#38]
Could you add possibility to change inputs' font ? This doesn't seem to work for now: 

![CleanShot 2023-06-07 at 15 45 31](https://github.com/checkout/frames-react/assets/7773454/0e62460b-05f5-4421-9dd1-31b1341e8ee4)
![CleanShot 2023-06-07 at 15 45 35](https://github.com/checkout/frames-react/assets/7773454/5bce934b-b9f2-4ce9-93bf-0ed9a52ea9d8)

**Comment by ioan-ghisoi-cko** [comment]
Closing this issue as this package will soon be deprecated. A new version using [Checkout.com Flow](https://www.checkout.com/docs/payments/accept-payments/accept-a-payment-on-your-website/get-started-with-flow) is currently in the works.

Fonts: Since Frames renders iFrame components, the only fonts supported are web safe fonts.
